---
- name: My first play
  hosts: all
  # Disable gathering facts, we're going to do it explicitly.
  gather_facts: false
  become: true
  tasks:
    # Gather facts and store the result in the new variable 'setup_result'.
    - name: Gather facts
      ansible.builtin.setup:
      register: setup_result

    - name: Show facts
      ansible.builtin.debug:
        var: setup_result

    - name: Ping
      ansible.builtin.ping:

    - name: Copy important file
      ansible.builtin.copy:
        src: important.txt
        dest: /home/vagrant/important.txt
        owner: vagrant
        group: vagrant
        mode: "0644"

    - name: Copy important template
      ansible.builtin.template:
        src: important.txt.j2
        dest: /home/vagrant/important-template.txt
        owner: vagrant
        group: vagrant
        mode: "0644"

    - name: Set http_proxy
      ansible.builtin.lineinfile:
        path: /etc/environment
        line: http_proxy=http://{{ ansible_default_ipv4.gateway }}:9000
      when: use_corp_http_proxy

    - name: Loop with multiple tasks to create and fill directories
      ansible.builtin.include_tasks:
        file: tasks/loop_dir.yml
      loop: "{{ product_dirs }}"
      tags:
        - dirs
