---
- name: My first play
  hosts: all
  # Disable gathering facts, we're going to do it explicitly.
  gather_facts: false
  become: true
  tasks:
    # Gather facts and store the result in the new variable 'setup_result'.
    - name: Gather facts
      ansible.builtin.setup:
      register: setup_result
      tags: always

    - name: Show facts
      ansible.builtin.debug:
        var: setup_result

    - name: Ping
      ansible.builtin.ping:

    - name: Copy important file
      ansible.builtin.copy:
        src: important.txt
        dest: /home/vagrant/important.txt
        owner: vagrant
        group: vagrant
        mode: "0644"

    - name: Copy important template
      ansible.builtin.template:
        src: important.txt.j2
        dest: /home/vagrant/important-template.txt
        owner: vagrant
        group: vagrant
        mode: "0644"

    - name: Set http_proxy
      ansible.builtin.lineinfile:
        path: /etc/environment
        line: http_proxy=http://{{ ansible_default_ipv4.gateway }}:9000
      when: use_corp_http_proxy

    - name: Loop with multiple tasks to create and fill directories
      ansible.builtin.include_tasks:
        file: tasks/loop_dir.yml
      loop: "{{ product_dirs }}"
      tags:
        - dirs

    - name: Start and enable firewalld
      ansible.builtin.service:
        name: firewalld
        state: started
        enabled: true

    - name: Open port 80
      ansible.posix.firewalld:
        service: http
        permanent: true
        state: enabled
      notify: Reload firewalld
      tags: firewalld

    - name: Install httpd
      ansible.builtin.yum:
        name: httpd
        state: present
        update_cache: true
      tags: httpd

    - name: Start and enable httpd
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: true
      tags: httpd

    - name: Check that we can connect to port 80
      ansible.builtin.wait_for:
        host: "{{ ansible_host }}"
        port: 80
        timeout: 2
      tags: httpd

    - name: Create /var/www/html/
      ansible.builtin.file:
        path: /var/www/html/
        owner: root
        group: root
        mode: "0775"
        state: directory

    - name: Create /var/www/html/index.html
      ansible.builtin.copy:
        dest: /var/www/html/index.html
        content: |
          <html>
            <h1>Welcome!</h1>
            <p>To {{ ansible_distribution ~ ' ' ~ ansible_distribution_version }}</p>
          </html>
        owner: root
        group: root
        mode: "0775"
      tags: httpd

    - name: Test that we can access the page
      ansible.builtin.uri:
        url: http://{{ ansible_host }}
        return_content: true
        status_code:
          - 200
      register: uri_result
      failed_when: "'Welcome!' not in uri_result.content"
      tags: httpd

  handlers:
    - name: Reload firewalld
      ansible.builtin.service:
        name: firewalld
        state: reloaded
